services:
  web:
    build: .
    container_name: my_flask_app
    ports:
      - "8080:5000"
    depends_on:
      - db
    volumes:
      - ./app:/app

  db:
    image: postgres:latest
    container_name: my_postgres_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mytodos
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
