services:
  python3:
    build: .
    container_name: Smartphone-EasyPCCP-Plan
    tty: true
    working_dir: "/app"
    volumes:
        - .:/app
    ports:
      - "5000:5000"
    command: /usr/local/bin/gunicorn -k gevent --reload --workers 10 --worker-connections 10 --access-logfile=- --pythonpath /app -b :5000 app:app